ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'COMMENT_MENTIONED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'COMMENT_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ISSUE_DELETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ATTACHMENT_UPLOADED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ATTACHMENT_DELETED';